import { Capacitor } from "@capacitor/core";
import { Printer } from "@capgo/capacitor-printer";
import { formatDate } from "@utils/date";

export interface PrintTableColumn {
  key: string;
  label: string;
}

export interface PrintDocumentPayload {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  summary?: Array<{ label: string; value: string | number }>;
  columns: PrintTableColumn[];
  rows: Array<Record<string, string | number | null | undefined>>;
}

const escapeHtml = (value: string | number | null | undefined): string => {
  const text = String(value ?? "");
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
};

const renderSummary = (summary: PrintDocumentPayload["summary"] = []) => {
  if (summary.length === 0) return "";
  return `
    <div class="summary-grid">
      ${summary
        .map(
          (item) => `
        <div class="summary-item">
          <div class="summary-label">${escapeHtml(item.label)}</div>
          <div class="summary-value">${escapeHtml(item.value)}</div>
        </div>
      `
        )
        .join("")}
    </div>
  `;
};

const buildHtml = (payload: PrintDocumentPayload) => {
  const today = formatDate(new Date().toISOString());
  const tableHead = payload.columns.map((col) => `<th>${escapeHtml(col.label)}</th>`).join("");
  const tableRows = payload.rows
    .map(
      (row) => `
      <tr>
        ${payload.columns.map((col) => `<td>${escapeHtml(row[col.key])}</td>`).join("")}
      </tr>
    `
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(payload.title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; color: #1a1025; padding: 28px; }
    .header { margin-bottom: 16px; }
    .title { font-size: 22px; font-weight: 700; color: #3d004c; }
    .subtitle { margin-top: 4px; font-size: 13px; color: #6b5f77; }
    .meta { margin-top: 6px; font-size: 12px; color: #7b6e89; }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
      gap: 10px;
      margin: 14px 0 18px;
    }
    .summary-item {
      border: 1px solid #e6deeb;
      border-radius: 8px;
      padding: 10px;
      background: #faf7fc;
    }
    .summary-label { font-size: 11px; color: #7b6e89; text-transform: uppercase; }
    .summary-value { margin-top: 3px; font-size: 15px; font-weight: 700; color: #3d004c; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #e6deeb; padding: 9px 10px; text-align: left; font-size: 12px; }
    th { background: #f3e6f8; color: #3d004c; font-weight: 700; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">${escapeHtml(payload.title)}</div>
    ${payload.subtitle ? `<div class="subtitle">${escapeHtml(payload.subtitle)}</div>` : ""}
    <div class="meta">
      Printed on ${escapeHtml(today)}${payload.generatedBy ? ` · Generated by ${escapeHtml(payload.generatedBy)}` : ""}
    </div>
  </div>
  ${renderSummary(payload.summary)}
  <table>
    <thead><tr>${tableHead}</tr></thead>
    <tbody>${tableRows || `<tr><td colspan="${payload.columns.length}">No records found.</td></tr>`}</tbody>
  </table>
</body>
</html>`;
};

async function printDocument (payload: PrintDocumentPayload) {
  const html = buildHtml(payload);

  if (Capacitor.isNativePlatform()) {
    await Printer.printHtml({ name: payload.title, html });
    return;
  }

  const existing = document.getElementById("__print_frame__");
  if (existing) existing.remove();

  const iframe = document.createElement("iframe");
  iframe.id = "__print_frame__";
  iframe.style.cssText = "position:fixed;top:0;left:0;width:1px;height:1px;border:none;opacity:0;pointer-events:none;";
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) return;

  doc.open();
  doc.write(html);
  doc.close();

  iframe.onload = () => {
    setTimeout(() => {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
      setTimeout(() => iframe.remove(), 1500);
    }, 300);
  };
};

export default printDocument;
